rpc:
  host: 'localhost:10001'
  username: 'test'
  password: 'test'
db:
  driverClassName: 'org.h2.Driver'
  url: 'jdbc:h2:~/h2'
  username: 'test'
  password: 'test'
spring:
  jpa.generate-ddl: true
